name: Deploy/gh-pages

on: 
  push:
    branches:
      - main
jobs: 
  build:
    name: Publish build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 20.8.1
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install independecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          folder: build
          branch: docs
      